export default [
    {
        name:'PALAPA',
        iconType:'Material',
        iconName:'face-profile'
    },
    {
        name:'Keberangkatan',
        iconType:'Material',
        iconName:'bookmark-check-outline'
    },
    {
        name:'Kepulangan',
        iconType:'Material',
        iconName:'bookmark-check-outline'
    },
    {
        name:'Imigrasi',
        iconType:'FontAwesome5',
        iconName:'user-friends'
    },
    {
        name:'News',
        iconType:'Feather',
        iconName:'settings'
    },
    {
        name:'Restoran Indonesia',
        iconType:'FontAwesome5',
        iconName:'user-friends'
    },
    {
        name:'Kontak',
        iconType:'FontAwesome5',
        iconName:'user-friends'
    },
 ]