export default [
    {
        name:'PPIUK',
        iconType:'Material',
        iconName:'home'
    },
    {
        name:'Keberangkatan',
        iconType:'MaterialIcons',
        iconName:'flight-takeoff'
    },
    {
        name:'Kepulangan',
        iconType:'MaterialIcons',
        iconName:'flight-land'
    },
    {
        name:'Imigrasi',
        iconType:'FontAwesome5',
        iconName:'passport'
    },
    {
        name:'News',
        iconType:'FontAwesome',
        iconName:'newspaper-o'
    },
    {
        name:'Events',
        iconType:'MaterialIcons',
        iconName:'event'
    },
    {
        name:'Restoran Indonesia',
        iconType:'Ionicons',
        iconName:'restaurant-outline'
    },
    {
        name:'Kontak',
        iconType:'Ant',
        iconName:'contacts'
    },
 ]